name: 'CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm i

      - name: Build library
        run: npm run build:lib

      - name: Build playground
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm i

      - name: Test library
        run: npm run test:lib:headless
